# Generated by Django 5.1.7 on 2025-04-03 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0012_ganswer_file_url_ganswer_image_ganswer_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='gquestion',
            name='allow_attachments',
            field=models.BooleanField(default=False),
        ),
    ]
