# Generated by Django 5.1.7 on 2025-04-03 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0013_gquestion_allow_attachments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gquestion',
            name='allow_attachments',
        ),
    ]
