# Generated by Django 5.1.7 on 2025-04-03 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0014_remove_gquestion_allow_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='gquestion',
            name='allow_attachments',
            field=models.BooleanField(default=False, help_text='Permitir que los usuarios adjunten archivos o URLs a esta pregunta'),
        ),
    ]
