# Generated by Django 5.1.7 on 2025-04-03 23:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0016_gquestion_created_by_gquestion_in_question_bank_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gquestion',
            name='in_question_bank',
        ),
        migrations.RemoveField(
            model_name='gquestion',
            name='usage_count',
        ),
        migrations.CreateModel(
            name='BankQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=500)),
                ('question_type', models.CharField(choices=[('short_text', 'Texto Corto'), ('paragraph', 'Párrafo'), ('multiple_choice', 'Opción Múltiple'), ('checkbox', 'Casillas de Verificación'), ('dropdown', 'Lista Desplegable'), ('linear_scale', 'Escala Lineal'), ('date', 'Fecha'), ('time', 'Hora')], max_length=20)),
                ('help_text', models.CharField(blank=True, max_length=255, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('min_value', models.IntegerField(blank=True, default=1, null=True)),
                ('max_value', models.IntegerField(blank=True, default=5, null=True)),
                ('min_label', models.CharField(blank=True, max_length=50, null=True)),
                ('max_label', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bank_question_images/')),
                ('allow_attachments', models.BooleanField(default=False, help_text='Permitir que los usuarios adjunten archivos o URLs a esta pregunta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_questions_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('position', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='checklist.bankquestion')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='gquestion',
            name='bank_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_questions', to='checklist.bankquestion'),
        ),
    ]
