# Generated by Django 5.1.7 on 2025-04-08 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0019_bankquestion_last_modified_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankquestion',
            name='last_modified_date',
        ),
    ]
