# Generated by Django 5.1.7 on 2025-04-09 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0020_remove_bankquestion_last_modified_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gquestion',
            name='created_by',
        ),
    ]
