# Generated by Django 5.1.7 on 2025-04-11 18:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0021_remove_gquestion_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('permission_type', models.CharField(choices=[('editor', 'Editor'), ('responder', 'Respondedor'), ('viewer', 'Visualizador')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='checklist.gform')),
            ],
        ),
        migrations.CreateModel(
            name='FormPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('editor', 'Editor'), ('responder', 'Respondedor'), ('viewer', 'Visualizador')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='checklist.gform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('form', 'user')},
            },
        ),
    ]
