# Generated by Django 5.1.7 on 2025-03-22 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0005_dynamicform_formresponse_question_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectedoption',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='dynamicform',
            name='user',
        ),
        migrations.RemoveField(
            model_name='question',
            name='form',
        ),
        migrations.RemoveField(
            model_name='formresponse',
            name='form',
        ),
        migrations.RemoveField(
            model_name='formresponse',
            name='respondent',
        ),
        migrations.RemoveField(
            model_name='questionoption',
            name='question',
        ),
        migrations.RemoveField(
            model_name='selectedoption',
            name='option',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='DynamicForm',
        ),
        migrations.DeleteModel(
            name='FormResponse',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionOption',
        ),
        migrations.DeleteModel(
            name='SelectedOption',
        ),
    ]
