# Generated by Django 5.1.7 on 2025-03-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0007_answer_answerfile_dynamicform_formresponse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='answer_media/'),
        ),
        migrations.AddField(
            model_name='answer',
            name='media_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='question_media/'),
        ),
        migrations.AddField(
            model_name='question',
            name='media_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='option_images/'),
        ),
        migrations.AddField(
            model_name='selectedoption',
            name='column',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selectedoption',
            name='row',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
