# Generated by Django 5.1.7 on 2025-03-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0011_gform_gquestion_goption_gresponse_ganswer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ganswer',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ganswer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gform_answer_images/'),
        ),
        migrations.AddField(
            model_name='ganswer',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='gform_answer_videos/'),
        ),
    ]
